use super::*;

#[test]
fn family_configs_expose_resize_kernel_decisions() {
    assert_eq!(
        BlipImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::CatmullRom
    );
    assert_eq!(
        ClipImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::CatmullRom
    );
    assert_eq!(
        QwenVlImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::CatmullRom
    );
    assert_eq!(
        LlavaNextImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::CatmullRom
    );
    assert_eq!(
        PixtralImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::CatmullRom
    );
    assert_eq!(
        Idefics3ImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Lanczos3
    );
    assert_eq!(
        Gemma3ImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        MllamaImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        VitImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        DetrImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        SamImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        DocumentOcrImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        VideoMaeImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        VivitImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        VaeImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Lanczos3
    );
    assert_eq!(
        Flux2ImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Lanczos3
    );
    assert_eq!(
        VisualClozeProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Lanczos3
    );
    assert_eq!(
        HunyuanVideo15ImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Lanczos3
    );
    assert_eq!(
        MarigoldImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
    assert_eq!(
        JoyImageEditImageProcessorConfig::default()
            .resize_decision()
            .kernel(),
        ResizeKernel::Triangle
    );
}

#[test]
fn family_configs_default_to_compatibility_resize_parity() {
    assert_eq!(
        BlipImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        VaeImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        Flux2ImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        VisualClozeProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        HunyuanVideo15ImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        MarigoldImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        ClipImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        VitImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        QwenVlImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        LlavaNextImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        PixtralImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        Idefics3ImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        Gemma3ImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        MllamaImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        JoyImageEditImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
    assert_eq!(
        WanAnimateImageProcessorConfig::default()
            .image_processor_config()
            .resize_parity,
        ResizeParity::Compatibility
    );
}
